language: php

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
      # Minimum supported versions
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-lowest"
      ## with sodium extension installed.
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-lowest"
      before_install:
        - sudo add-apt-repository ppa:ondrej/php -y
        - sudo apt-get -qq update
        - sudo apt-get install -y libsodium-dev
        - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
        - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
      install:
        - printf "\n" | pecl install libsodium
        - composer update $COMPOSER_FLAGS --prefer-dist --no-interaction

    - php: 7.3
      env: COVERAGE=true PHPUNIT_FLAGS="-v --coverage-text"

      # Latest commit to master
    - php: 7.3
      env: STABILITY="dev"

  allow_failures:
    # Dev-master is allowed to fail.
    - env: STABILITY="dev"

branches:
  only:
    - master
    - travis
    # Build maintenance branches for older releases if needed. such branches should be named like "1.2"
    - '/^\d+\.\d+$/'

before_install:
    - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
    - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;

install:
  - composer update $COMPOSER_FLAGS --prefer-dist --no-interaction

script:
  - composer validate --strict --no-check-lock
  - vendor/bin/phpunit $PHPUNIT_FLAGS
